name: Create Web App and Deploy the Application  
on:
  workflow_dispatch:

jobs:
  create-and-build-web-app:   
    runs-on: ubuntu-latest
    env:
      # Resource Group 
      RG_NAME: inbrein-azure-ml-research
      
      # Azure Container Registry 
      ACR_NAME: eunsangacr
      ACR_URL: eunsangacr.azurecr.io 
      ACR_IMAGE_NAME: automl-in-webapp
      
      # App Service Plan 
      ASP_NAME: automl-webapp-service-plan
      ASP_REGION: koreacentral
      ASP_SKU: p1v3

      # Web App 
      WA_NAME: automl-webapp 
      
    steps:
    - name: Log in to Azure CLI
      uses: azure/login@v2.1.0
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Log in to Azure Container Registry
      run: |
        az acr login --name ${{ env.ACR_NAME }}
    
    # - name: Create an App Service Plan 
    #   run: |
    #     az appservice plan create \
    #       --resource-group ${{ env.RG_NAME }} \
    #       --name ${{ env.ASP_NAME }} \
    #       --location ${{ env.ASP_REGION }} \
    #       --hyper-v \
    #       --sku ${{ env.ASP_SKU }}
    
    # - name: Create a Web App (without image)
    #   run: |
    #     az webapp create \
    #       --name ${{ env.WA_NAME }} \
    #       --plan ${{ env.ASP_NAME }} \
    #       --resource-group ${{ env.RG_NAME }} \
    #       --basic-auth Enabled

    # - name: Enable Managed Identity for the Web App
    #   run: |
    #     az webapp identity assign \
    #       --resource-group ${{ env.RG_NAME }} \
    #       --name ${{ env.WA_NAME }}
    
    - name: Assign AcrPull role to Web App Managed Identity
      run: |
        WEB_APP_PRINCIPAL_ID=$(az webapp identity show --name ${{ env.WA_NAME }} --resource-group ${{ env.RG_NAME }} --query principalId --output tsv)
        
        az role assignment create \
          --assignee $WEB_APP_PRINCIPAL_ID \
          --scope /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/${{ secrets.RG_NAME }} \
          --role "AcrPull"
    
    - name: Deploy the Container Image to Web App
      run: |
        az webapp config container set \
          --name ${{ env.WA_NAME }} \
          --resource-group ${{ env.RG_NAME }} \
          --container-image-name ${{ env.ACR_URL }}/${{ env.ACR_IMAGE_NAME }}:latest \
          --container-registry-url https://${{ env.ACR_URL }}
    
    - name: Restart Web App to Apply Changes
      run: |
        az webapp restart \
          --name ${{ env.WA_NAME }} \
          --resource-group ${{ env.RG_NAME }}
